### ISSUE TITLE
Input field working strangely, and doesn't allow to edit the JSON

### ISSUE THREAD

**Issue by zycon** [dolevf/Open-Policy-Agent-Alfred#2]
![CleanShot 2023-12-19 at 23 15 45](https://github.com/dolevf/Open-Policy-Agent-Alfred/assets/36449874/c1750920-648b-44f4-82c5-ac220a04e474)
Not sure this is because of this exception am getting, the thing is cursor acting so strangely while trying to edit the INPUT json field

**Comment by dolevf** [comment]
Can you clarify what "cursor acting strangely" mean?

**Comment by zycon** [comment]
https://github.com/dolevf/Open-Policy-Agent-Alfred/assets/36449874/1e413175-770b-45c6-9f16-7ac049471b60

specifically to column while for the json key value

**Comment by dolevf** [comment]
I'm not able to replicate this, can you try to use the latest Docker hub image?

`docker pull dolevf/alfred:latest`

**Comment by dolevf** [comment]
Closing, please feel free to reopen if relevant.
